name: distributed-inference
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.3.1
      - deepspeed==0.14.4
      - transformers==4.43.3
      - tokenizers==0.19.1
      - sentencepiece==0.2.0
      - accelerate==0.30.1
      - huggingface-hub==0.23.4
      - hjson==3.1.0
      - tqdm>=4.66
      - psutil>=5.9
      - pyyaml
      - packaging
      - ninja>=1.11
      - requests>=2.31
      - filelock>=3.12
      - regex>=2024.4
      - safetensors>=0.4.1
      - fsspec>=2023.5.0
      - pydantic==2.12.5
      - typing-inspection>=0.4.2
      - py-cpuinfo>=9.0.0
      - typing_extensions>=4.9
      - certifi>=2024.2.0
      - charset-normalizer>=3.3.0
      - idna>=3.6
      - urllib3>=2.1.0
      - numpy>=1.23
